### ISSUE TITLE
Add creating a canary on push into release in deploy.yml 

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-npm#867]
Currently we only create a canary build on commit into develop. However, there is a chance that the commits in develop were never pushed into the release branch for QA. To mitigate this use case, we need to also build a canary when a push to the release branch happens, so QA is always testing the correct codeset that will be deployed. 

In deploy.yaml,
```
on:
  push:
    branches:
      - develop
      - master
```
needs to be 
```
on:
  push:
    branches:
      - develop
      - release
      - master
```

AND

```
canary:
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop' && github.repository_owner == 'dequelabs'
```
needs to be
```
canary:
    runs-on: ubuntu-latest
    if: (github.ref_name == 'develop' || github.ref_name == 'release') && github.repository_owner == 'dequelabs'
```
